openapi: "3.0.0"
info:
  title: Harmonizer
  version: 0.0.1
paths:
  /authenticate:
    post:
      operationId: routes.authenticate
      responses:
        '200':
          description: "Connexion de l'utilisatuer"
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password_hash
          in: query
          required: true
          schema:
            type: string