openapi: "3.0.0"
info:
  title: Harmonizer
  version: 0.0.1
paths:
  /authenticate:
    get:
      operationId: routes.authenticate
      responses:
        '200':
          description: "Connexion de l'utilisateur"
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password_hash
          in: query
          required: true
          schema:
            type: string

  /validateToken:
    get:
      operationId: routes.validateToken
      responses:
        '200':
          description: "Connexion de l'utilisateur"
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string


  /createAccount:
    post:
      operationId: routes.createAccount
      responses:
        '200':
          description: "Création du compte de l'utilisateur"
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password_hash
          in: query
          required: true
          schema:
            type: string

  /harmonize:
    post:
      operationId: routes.harmonize
      responses:
        '200':
          description: "harmonisation d'une image"
      parameters:
        - name: token
          in: query
          required: false
          schema:
            type: string
        - name: template
          in: query
          required: false
          schema:
            type: string
        - name: angle
          in: query
          required: false
          schema:
            type: number

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary