openapi: "3.0.0"
info:
  title: Harmonizer
  version: 0.0.1
paths:
  /authenticate:
    get:
      operationId: routes.authenticate
      responses:
        '200':
          description: "Connexion de l'utilisateur"
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password_hash
          in: query
          required: true
          schema:
            type: string

  /createAccount:
    post:
      operationId: routes.createAccount
      responses:
        '200':
          description: "Créationdu compte de l'utilisateur"
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password_hash
          in: query
          required: true
          schema:
            type: string

